#Deployment+Load Balancer:

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: nginx-lb
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: nginx-lb
  template:
    metadata:
      labels:
        app: nginx-lb
    spec:
      containers:
      - name: nginx-containers
        image: nginx
        ports:
          containerPort: 8080
---

# Load Balancer service

apiVersion: v1
kind: Service
metadata:
  name: nginxlb-service
  labels:
    app: nginx-lb
spec:
  selector:
    app: nginx-lb
  type: LoadBalancer
  ports:
  - nodeport: 31001
    port: 80
    targetPort: 8080
    