# Nodeport with Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: nginx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.16
        port:
        - containerPort: 8080
---

#Node Port service:

apiVersion: v1
kind: Service
metadata: 
  name: nginx-service
  labels:
    app: nginx-app
spec:
  selector:
    app: nginx-app
  type: NodePort
  ports:
  - nodeport: 30010  
    port: 80
    targetPort: 8080
---     